export const LOAD_TOP_HEADLINES_SUCCESS = "LOAD_TOP_HEADLINES_SUCCESS";
export const SEARCH_HEADLINES_SUCCESS = "SEARCH_HEADLINES_SUCCESS";
export const SET_CURRENT_ARTICLE = "SET_CURRENT_ARTICLE";
export const SET_API_CALL_LOADING = "SET_API_CALL_LOADING";
